export const turtles = [
  {
    id:1,
    name: 'loggerhead',
    portugueseName: 'Tartaruga Comum',
    scientificName: 'Caretta caretta',
    SVGIcon: '/turtles/loggerhead.svg',
    distribution: '/map/distribution/loggerhead.svg'
  },
  {
    id:2,
    name: 'green turtle',
    portugueseName: 'Tartaruga-verde',
    scientificName: 'Chelonia mysdas',
    SVGIcon: '/turtles/greenTurtle.svg',
    distribution: '/map/distribution/greenTurtle.svg',
  },
  {
    id:3,
    name: 'leatherback',
    portugueseName: 'Tartaruga-de-couro',
    scientificName: 'Dermochelys coriacea',
    SVGIcon: '/turtles/leatherback.svg',
    distribution: '/map/distribution/leatherback.svg',
  },
  {
    id:4,
    name: 'hawksbill',
    portugueseName: 'Tartaruga-de-pente',
    scientificName: 'Eretmochelys imbricata',
    SVGIcon: '/turtles/hawksbill.svg',
    distribution: '/map/distribution/hawksbill.svg',
  },
  {
    id:5,
    name: 'kemps Ridley',
    portugueseName: 'Tartaruga-de-kemp',
    scientificName: 'Lepidochelys kempii',
    SVGIcon: '/turtles/kempsRidley.svg',
    distribution: '/map/distribution//kempsRidley.svg',
  },
  {
    id:6,
    name: 'Olive Ridley',
    portugueseName: 'Tartaruga-oliva',
    scientificName: 'Lepidochelys olivacea',
    SVGIcon: '/turtles/oliveRidley.svg',
    distribution: '/map/distribution//oliveRidley.svg',
  },
  {
    id:7,
    name: 'flatback',
    portugueseName: 'Tartaruga-marinha-australiana',
    scientificName: 'Natator depressus',
    SVGIcon: '/turtles/flatback.svg',
    distribution: '/map/distribution/flatback.svg',
  },
];